version: "3.9"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always