import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '../components/common/Footer/Footer'
import Advantages from '@/components/Advantages/Advantages'
import About from '@/components/About/About'
import HowToStart from '@/components/HowToStart/HowToStart'
import SocialMedia from '@/components/SocialMedia/SocialMedia'
import FAQ from '@/components/FAQ/FAQ'
import Header from '@/components/common/Header/Header'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href='index.css' />
      </Head>
      <header className={styles.header}>
        <Header />
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <About />
        <Advantages />
        <HowToStart />
        <SocialMedia />
        <FAQ />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </>
  )
}
